### ISSUE TITLE
z-index issue with DateTime field

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/AdminThemeUikit#1]
![screenshot 2017-03-04 07 29 43_cr](https://cloud.githubusercontent.com/assets/7663992/23576852/905e82fe-00b0-11e7-8d73-0431889cee73.png)

`<div id="ui-datepicker-div" class="ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all" style="position: absolute; top: 1648px; left: 60px; z-index: 1; display: block;">...</div>`

`
element.style {
  position: absolute;
  top: 1648px;
  left: 60px;
  z-index: 1;
  display: block;
}
`

Setting z-index to higher value like 10 solves the issue.

**Comment by ryancramerdesign** [comment]
I wasn't able to duplicate this. I setup it to look like your screenshot above, but the datepicker appeared above the images field, not below or within it like in your screenshot. Is there anything else necessary to duplicate that, like does it occur after an upload or sort operation or something?

**Comment by matjazpotocnik** [comment]
In the InputfieldImage.css there is:

```
.InputfieldImageEditAll .gridImage__overflow {
  position: relative;
	z-index: 2;
	...
}
.InputfieldImageEditAll .gridImage .ImageData {
  ...
  z-index: 3;
}
```

while created 

`<div id="ui-datepicker-div" ... </div>` has inline style with ` z-index: 1`

It doesn't matter if image is uploaded or the image is there before, sorting is also not imaportant. You must have the view set to "list", while "grid" and "left" views are ok. It's interesting that this behaviour is not present in the Default admin theme.

**Comment by matjazpotocnik** [comment]
I fixed this by adding `z-index: 999!important;` to `#ui-datepicker-div` in InputfieldDatetime.css

**Comment by matjazpotocnik** [comment]
@ryancramerdesign, any chance of fixing this?

**Comment by swcarrey** [comment]
This is quite an issue for me too:

[PW forum thread here](https://processwire.com/talk/topic/18029-adminthemeuikit-datetime-field-bug/?tab=comments)

**Comment by EarlThorfinn** [comment]
I believe I’ve encountered the same bug today, with AdminThemeUikit v0.2.2 on ProcessWire 3.0.93 and testing in multiple browsers.  

Screenshot:
![screen shot 2018-02-24 at 20 16 40](https://user-images.githubusercontent.com/7932180/36634668-e50d1ce4-199f-11e8-93c4-f095c786a8ad.png)

As matjazpotocnik points out above, the issue appears to be with z-index for #ui-datepicker-div.  Adding z-index: 3 !important to #ui-datepicker-div in the web inspector fixes in my browsers.

**Comment by matjazpotocnik** [comment]
Fixed https://github.com/processwire/processwire/commit/16f614f5a0ee8c4a157fe92fd3c8e93b1e1cbbdd
