### ISSUE TITLE
Extra page list action buttons need some vertical offset in Page Tree sidebar

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/AdminThemeUikit#10]
A little vertical space would be nicer:

![screen shot 2017-03-17 at 12 30 56 pm](https://cloud.githubusercontent.com/assets/871211/24059805/9a1fefa0-0b0d-11e7-9e5e-ba73c69f3838.png)

**Comment by ryancramerdesign** [comment]
I've been unable to figure out how to do this, and spent quite a bit of time with it earlier this week. I think maybe we need someone with more front-end dev abilities than me. As soon as I get the margins right, hovering the page list causes annoying line-height problems. That ends up being a bigger annoyance. So I've left it as-is for now, but if you have any ideas how to make it work, or know someone that does, I agree it would be nice to update.

**Comment by adrianbj** [comment]
I think @rolandtoth (tpr) is our man here :)

**Comment by rolandtoth** [comment]
Setting the line-height from `1em` to `1.4` on the element `.PageListActions.actions` seem to solve the issue.

**Comment by adrianbj** [comment]
@rolandtoth - looks good to me - thanks!

**Comment by ryancramerdesign** [comment]
Thanks very much @rolandtoth that seems to solve it! Such a nice simple solution.

**Comment by adrianbj** [comment]
Looks great in v6 - thanks!
