### ISSUE TITLE
Button padding missing

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/AdminThemeUikit#15]
I think this started in the version committed last Friday. It looks fine initially, but some JS kicks in and removes the padding.

![screen shot 2017-03-27 at 10 33 05 am](https://cloud.githubusercontent.com/assets/871211/24369456/eb012bfa-12d8-11e7-9d00-73062ee77d86.png)

Unrelated, but since it's in this screenshot - I feel like the h1 at 2.625rem is just too big. I think 2 is OK, and maybe drop h2 down to 1.6?

**Comment by ryancramerdesign** [comment]
I've not observed that here and not seeing it now either. You mentioned
some JS kicking in, is it possible something else non-core is doing it?
Regarding things like font sizes in headlines, I'm not trying to get into
subjective things like that for this project–I think better to stick with
stock UIKit and let the designers get into those kinds of details. Though I
do agree, UIKit stock styles have always had larger headlines than I
prefer.

**Comment by adrianbj** [comment]
Sorry about that - turns out it was a Chrome browser extension that was affecting the buttons - weird :)

Fair enough on the font sizes!
