### ISSUE TITLE
Search icon encoding issue in Safari

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/AdminThemeUikit#18]
Just noticed this in Safari (it's fine in Chrome). 

![screen shot 2017-03-31 at 8 28 51 am](https://cloud.githubusercontent.com/assets/871211/24557374/51e51028-15ec-11e7-9195-46efc40545a0.png)

**Comment by ryancramerdesign** [comment]
Adrian, I'm not seeing this issue in Safari. However, I have noticed during development that every once in awhile (pretty rarely), the icons go haywire, and a refresh resolves it. Maybe there is some issue with the Uikit 3 beta, but I don't think we'll worry about this one unless it continues after Uikit is out of beta.

**Comment by adrianbj** [comment]
No problem - it's working today - who knows :) I close this for now.

**Comment by ryancramerdesign** [comment]
I think you must have taken my icons then, because now icons are not working for me in Safari no matter how many times I reload.

**Comment by adrianbj** [comment]
LOL :)
