### ISSUE TITLE
Icons option for Page list actions

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/AdminThemeUikit#20]
This is something that @rolandtoth has built into AdminOnSteroids, but I think it would make a useful core addition for the sidebar layout as it lets you have a much narrower sidebar width without actions wrapping to a new line.

![screen shot 2017-04-03 at 8 33 16 am](https://cloud.githubusercontent.com/assets/871211/24617465/cd95326c-1848-11e7-8cb2-29569e2988cd.png)

PS - Roland - the icons don't currently work in the sidebar.

**Comment by rolandtoth** [comment]
Icons can shorten the row significantly but for the sidebar it's maybe not the best solution, rows will go multiline anyways.

What I can imagine is collapsing all actions into one drop down button (or maybe Edit+ others), or move actions to a second row by default (maybe in the sidebar only). Neither one is perfect but maybe they can generate more ideas.

**Comment by adrianbj** [comment]
I like the idea of edit and a dropdown for the others!

I am not a fan of the action being on a second row though - either too much vertical space if always on, or if they appear on hover, then not much better than the current scenario which causes a shift.

**Comment by rolandtoth** [comment]
The "Edit+dropdown" would be perhaps better to place before the page title.

**Comment by ryancramerdesign** [comment]
The small dropdown option seems like a good route long term for the sidebar layout. It's little more work than I want to get into short term, but sounds good to me. With the current actions, I think that the click-to-reveal actions (as PW had in 2.6 and earlier) works a lot better because you aren't having things jumping all over the place as you move your mouse around in the list. So thinking it should use that as the default setting when a sidebar layout is present.

**Comment by adrianbj** [comment]
Just voting to NOT return to "click-to-reveal" for sidebar actions, especially if it results in the need to load children along with displaying the actions (but even if it doesn't). I like the hover and still find it annoying without full width hover (like AdminOnSteroids provides). I think we need "edit" available on mouseover on full row width, and some kind of dropdown for the others.

I know it's just my opinion, but still wanted to provide it :)

**Comment by ryancramerdesign** [comment]
You might have seen this already (was added a month or so ago) but the sidebar PageList now just shows "Edit" and "View" links, and all the others are in the extra actions. This helps a bit. I could always move the "View" action into the extra actions too.

**Comment by adrianbj** [comment]
Yeah, I did see the change, which definitely improves things. Unfortunately I don't think there is an ideal solution because some page names can just be too long to look good in the sidebar. I don't have any better ideas at the moment, so happy to close this.
