### ISSUE TITLE
Red <em> style ?

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/AdminThemeUikit#25]
Just wondering if this is intentional?
```
em {
    color: #f0506e;
}
```
It seems out of place to me. My Dynamic Description / Notes module allows for html in descriptions (along with PW field values and hanna code output), and now I am getting italic text showing up in that red/pink color.

**Comment by lesaff** [comment]
This is the default UIKit styling. I usually do this to override the default.
```
em {
    color: inherit;
}
```

**Comment by ryancramerdesign** [comment]
Where are you seeing the red em style? I'm thinking this one may have already been fixed, because just tested in a couple spots and not seeing it.

**Comment by adrianbj** [comment]
Yep, this is fixed now - thank you!
