### ISSUE TITLE
Collapsed checkbox fields not visible

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/AdminThemeUikit#26]
They work fine in the default PW theme, but they are completely invisible in UiKit theme. Maybe not just checkbox fields, but just noticed these are missing so reporting that.

**Comment by ryancramerdesign** [comment]
I think this one may also already be fixed, as I can't duplicate it it. Please let me know if you continue to see the issue. Thanks.

**Comment by adrianbj** [comment]
Thanks Ryan - looks to be fixed here also.
