### ISSUE TITLE
Error when i want to edit Fieldset and FieldsetTab close settings

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/AdminThemeUikit#3]
![ekran resmi 2017-03-05 01 06 49](https://cloud.githubusercontent.com/assets/455983/23582671/1547944c-0138-11e7-9122-d86957e864e3.png)

When i want to edit Fielset or FieldsetTab close field setting getting above error.

I edited line 203, for keep it working (when you have a fix i will update module files) :
```php
if($inputfield instanceof InputfieldWrapper || $inputfield instanceof InputfieldFieldsetClose) return;
````

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue.
