### ISSUE TITLE
Theme continues to apply to login screen even when option is unselected

### ISSUE THREAD

**Issue by Toutouwai** [ryancramerdesign/AdminThemeUikit#30]
Steps to reproduce:

1. Install AdminThemeUikit
2. In module settings, check "Use this admin theme for login screen?"
3. Logout and observe the Uikit theme applied to login (all good).
4. Login and in module settings uncheck "Use this admin theme for login screen?"
5. Logout and observe that the Uikit theme continues to be applied to the login screen.

**Comment by ryancramerdesign** [comment]
This one should already be fixed in the current version. Please let me know if you continue to see any issues. Thanks.

**Comment by Toutouwai** [comment]
Thanks
