### ISSUE TITLE
Remove mobile header

### ISSUE THREAD

**Issue by fbg13** [ryancramerdesign/AdminThemeUikit#32]
I think the mobile header is unnecessary. Instead of having a separate header add a class (pw-masthead-mobile) to the "default" header, hide everything but the logo and center the logo.

```
.pw-masthead-mobile .uk-navbar-container {
    height: 80px;
    justify-content: center;
}

.pw-masthead-mobile .pw-logo-link{
    margin-right: 0px!important;
}

.pw-masthead-mobile .uk-navbar-nav.pw-primary-nav,
.pw-masthead-mobile .uk-navbar-right {
    display: none;
}
```

**Comment by ryancramerdesign** [comment]
We want to keep these separate for now, as the plan is they'll likely go in a bit different directions down the road, so the separation gives us more flexibility. But will keep this in mind for the future if we don't end up doing that. Thanks.
