### ISSUE TITLE
Drop down of #pw-content-head-buttons has weird position sometimes

### ISSUE THREAD

**Issue by fbg13** [ryancramerdesign/AdminThemeUikit#33]
I'm moving the button in the header and the drop down has weird position sometimes.

Screenshot from [module edit](http://demo.processwire.com/regular/processwire/module/edit?name=AdminThemeUikit) page (looks weird).
![button dropdown wrong position](https://user-images.githubusercontent.com/6839895/30839529-397bf9c2-a27b-11e7-892f-828e8346fdff.png)

And from [page edit](http://demo.processwire.com/regular/processwire/page/edit/?id=1014) page.
![button dropdown correct position](https://user-images.githubusercontent.com/6839895/30839532-3c29151a-a27b-11e7-9088-8cee03b7a3b9.png)

You can also give it a right margin to test it `#pw-content-head-buttons { margin-right: 300px; }`

**Comment by ryancramerdesign** [comment]
I'm pretty sure jQuery UI determines where to show the menu depending on where it can find the most screen real estate. It changes depending on the situation. Both of the dropdown positions in the screenshots above look expected to me. But then again, I've not seen Submit/Save buttons in the masthead like that before, so don't know exactly what I'm looking at. :)

**Comment by fbg13** [comment]
> jQuery UI determines where to show the menu depending on where it can find the most screen real estate.

In both cases there was enough space for the drop-down on both sides.

I just checked it again (latest versions of PW and theme) and the drop-down is the same now (like in the second screenshot).
