### ISSUE TITLE
Enabling/Installing Notifications core module breaks the System Notifications

### ISSUE THREAD

**Issue by grimezy** [ryancramerdesign/AdminThemeUikit#37]
Enabling/Installing Notifications core module breaks the System Notifications using this theme.

I could replicate this with a clean install of v3.0.76, installing the Notifications core module and enabling the new AdminThemeUikit v0.1.4 via the user profile.

Attached are some screenshots.

![chrome_console](https://user-images.githubusercontent.com/18278963/31042164-faf938c8-a5e4-11e7-9d5d-e87e86347bdd.png)
![notification_area](https://user-images.githubusercontent.com/18278963/31042163-fae90246-a5e4-11e7-932a-664d5c9d2c2c.png)

Thanks.

**Comment by trk** [comment]
Notifications module not supported at the moment.

**Comment by trk** [comment]
You can find the module on, Modules => Core tab just uninstall it

**Comment by grimezy** [comment]
I can't as it states it's in use, and then trying to remove the field from the user template I run into the issue mentioned above.

![screen shot 2017-10-01 at 2 11 03 pm](https://user-images.githubusercontent.com/18278963/31051371-8264a6ee-a6b2-11e7-9351-50e23295daa2.png)

**Comment by trk** [comment]
There are 2 module, find main one for uninstall

**Comment by grimezy** [comment]
ahh, totally missed that, thank you so much!
