### ISSUE TITLE
Don't capitalize username

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/AdminThemeUikit#38]
I don't think the username should have ucfirst() applied to it:
https://github.com/ryancramerdesign/AdminThemeUikit/blob/db29a76a39cef06df25e00c82a3b6b2a1bc9b7aa/AdminThemeUikit.module#L632

I wouldn't mind seeing an option for replacing username with first_name and last_name fields though - maybe configurable in the module settings?

**Comment by adrianbj** [comment]
Actually, I just realized that it's not coming from ucfirst, it's a CSS capitalize:
https://github.com/ryancramerdesign/AdminThemeUikit/blob/db29a76a39cef06df25e00c82a3b6b2a1bc9b7aa/uikit/dist/css/uikit.pw.css#L4007

**Comment by franctic-aerobic** [comment]
And also capitalization of buttons is not preffered, as it also happens in other languages (e.g. Norwegian where titles are not supposed to be capitalized this way).

**Comment by ryancramerdesign** [comment]
The current version of the theme cancels out the default capitalize style from Uikit, but we do still do a ucfirst() on the username, for consistency with the rest of the navigation. Is this also problematic with other languages like Norwegian? I prefer capitalization consistency in the top navigation, but if it doesn't make sense with other languages, then we should probably remove that ucfirst() on the username per Adrian's suggestion.

**Comment by adrianbj** [comment]
I see why you may want it for visual consistency with the rest of the navigation, but  the other items in the nav are normal words, whereas the username is a made up string of letters that PW forces to be all lowercase when it is createed, so showing the first letter as uppercase just seems inconsistent (and a little ugly IMO).

**Comment by adrianbj** [comment]
Actually, I'd really like to see support for `first_name` and `last_name` like the Reno theme supports.That would solve this dilemma on some/many sites at least.

**Comment by PWaddict** [comment]
The capitalize css should be removed to display the "original" username.

**Comment by adrianbj** [comment]
Thanks Ryan for this and custom field and Gravatar support - looks much nicer!
