### ISSUE TITLE
Can you move uikit/custom folder to root of module ?

### ISSUE THREAD

**Issue by trk** [ryancramerdesign/AdminThemeUikit#4]
For make it easy to update uikit core files, can you move custom folder ? This way we can update uikit core files, by using copy => paste method easily.

This is my experience with uikit, when i design custom themes. Especially in this beta stage.

- AdminThemeUikit (root)
-- uikit
-- uikit-pw-theme

**Comment by ryancramerdesign** [comment]
I've just stuck to what the Uikit instructions said to do, as I'm no expert on the tools they are using to build and maintain it. I do a Uikit update via "git pull", which leaves the custom directory alone. I agree it would be nicer to just have it out of the UIkit structure completely though. Does everything still work moving that directory? I would think the commands like `npm run compile` would no longer be able to find it?

**Comment by trk** [comment]
I am using [bower](https://bower.io/) for update, download uikit and other frameworks, libraries, assets, and utilities and updating these libraries via bower.
```php
bower install uikit#^3.0.0
```

I forked this repo and updated folder structure https://github.com/trk/AdminThemeUikit
I used https://github.com/jonycheung/deadsimple-less-watch-compiler for compile less files via terminal
```php
less-watch-compiler less css pw.less
```

I added pw and uikit image paths as variable to pw.less file https://github.com/trk/AdminThemeUikit/commit/fa57ac187b4deaa73fef9cb30c25da086c1749ed#diff-65d0747e2334aecee498b952da18c0f4
updated logo and css path : https://github.com/trk/AdminThemeUikit/commit/fa57ac187b4deaa73fef9cb30c25da086c1749ed#diff-a74e52b0c0ae300658e7fac7f4b66c58
updated uikit.min.js file url and added uikit-icons.min.js : https://github.com/trk/AdminThemeUikit/commit/fa57ac187b4deaa73fef9cb30c25da086c1749ed#diff-b3e010471cfab9cba7898c33800a1b6b

If you wish to apply these changes, let me know. I can make a pull-request

**Comment by trk** [comment]
I updated forked repo and ranamed less files under less/pw/*.less, added "_" underscore prefix before filename.

This way when you compile less/pw.less file compiler won't compile less/pw/*.less files also, if files has "_" underscore prefix.

in your repo : https://github.com/ryancramerdesign/AdminThemeUikit/tree/master/uikit/custom/pw

You compiler also compiled most of less files.

**Comment by trk** [comment]
I am using your module with my own changes. I am trying to keep updated to my repo. I also added `npm` and `gulp`.

Anyway closing this issue. Nice work !
