### ISSUE TITLE
Comments Manager: Tabs not working

### ISSUE THREAD

**Issue by flydev-fr** [ryancramerdesign/AdminThemeUikit#43]
Tabs links in the _Comments Manager_ does not work when using AdminThemeUiKit. 

![comments-tabs](https://user-images.githubusercontent.com/11658616/31306108-3c666d58-ab49-11e7-8dcb-0c75171bf8ef.gif)

**Comment by ryancramerdesign** [comment]
This was a core issue and should be fixed in the latest version of the PW core (dev branch). Thanks.
