### ISSUE TITLE
Border type Card strange behaviour

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/AdminThemeUikit#44]
I have a title field Border set to Card and when next field is collapsed/expanded (toggled), the height of title is changed:

![jumping](https://user-images.githubusercontent.com/7663992/31310944-27b8f0de-aba2-11e7-8e89-e1848c61ccd3.gif)

**Comment by ryancramerdesign** [comment]
I'm not able to duplicate the issue here, but maybe this one has already been fixed via a Uikit version upgrade or some other changes in the thee. Please let me know if you are continuing to see it. Thanks.

**Comment by matjazpotocnik** [comment]
I still continue to see this issue. It's even worse if you have more fields where border is set to Card, see the gaps...

![card2](https://user-images.githubusercontent.com/7663992/32389520-2ac00f68-c0cb-11e7-9aec-36177d3cdae0.gif)

**Comment by matjazpotocnik** [comment]
This is still an issue in the latest uikit/pw, but I guess no one is using cards border, so I'll close this one.
