### ISSUE TITLE
Wrong class on Crop and Variations button

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/AdminThemeUikit#46]
In init.php, line 105, replace:

`'buttonClass' => "uk-button uk-button-small uk-button-text uk-margin-small-right",`

with

`'buttonClass' => "ui-button ui-corner-all ui-state-default",`

![screenshot 2017-10-08 10 25 20_cr](https://user-images.githubusercontent.com/7663992/31315252-9f1d3438-ac14-11e7-962c-e4dba5f2ca89.png)

Also, I find 12px font size used in `small .ui-button, small .ui-button.ui-state-default, small .ui-button.ui-state-hover {...}` to small.

**Comment by ryancramerdesign** [comment]
The intention is to use Uikit's text-only buttons here. I thought the regular buttons were just too much, too prominent relative to the actions. Those other buttons you see must be coming from a module. If you want the buttons to all appear the same, there's a couple ways that module could handle the button class. One would be to pull the class from PW's $config:
~~~~~
$a = $config->InputfieldImage;
if(is_array($a) && !empty($a['buttonClass'])) {
  $class = $a['buttonClass']; 
} else {
  $class = 'ui-button ui-state-default';
}
~~~~~
Another would be that it could force it to use the legacy themes button class, like your first screenshot:
~~~~~
$a = $config->InputfieldImage;
if(!is_array($a)) $a = array();
$a['buttonClass'] = 'ui-button ui-state-default';
~~~~~

**Comment by matjazpotocnik** [comment]
Ok, agree with font size.

Other buttons are coming from CI3 and AutoSmush modules, but this is not the issue. If you look at the markup, you'll see that classes are different, depending where the image is:

Crop button for image (example1):

```
<div class="InputfieldImageEdit__buttons"><small>
  <button type="button" data-href="/processwire/page/image/edit/?id=1015&amp;file=1015,zelenci-1-18.jpg&amp;rte=0&amp;field=imge" 
    class="InputfieldImageButtonCrop uk-button uk-button-small uk-button-text uk-margin-small-right pw-modal-large pw-modal"
    data-buttons="#non_rte_dialog_buttons button" data-autoclose="1" data-close="#non_rte_cancel">
    <span class="fa fa-crop"></span>
      Crop
  </button>
</small></div>
```
Result: 
![crop1](https://user-images.githubusercontent.com/7663992/32387355-8395dd72-c0c4-11e7-8e48-b90751dc6d95.jpg)



Crop button for image inside repeater or fieldsetpage (example2):

```
<div class="InputfieldImageEdit__buttons"><small>
  <button type="button" data-href="/processwire/page/image/edit/?id=1035&amp;file=1035,equations2.gif&amp;rte=0&amp;field=imge_repeater1035" 
    class="InputfieldImageButtonCrop ui-button ui-corner-all ui-state-default pw-modal-large pw-modal" 
    data-buttons="#non_rte_dialog_buttons button" data-autoclose="1" data-close="#non_rte_cancel">
    <span class="ui-button-text">
      <span class="fa fa-crop"></span>
       Crop
    </span>
  </button>
</small></div>

```
Result: 
![crop2](https://user-images.githubusercontent.com/7663992/32387368-8dc1628a-c0c4-11e7-8dc6-fe17eb9315da.jpg)

How should crop & variations buttons look like? Based on [demo site](http://demo.processwire.com/regular/processwire/), it should look like example1, but should look like example2 inside repeaters?

**Comment by processwired** [comment]
Tapped into this today. The look of crop & variations buttons is inconsistent, dependent if the image field is in a repeater or not. In my case the buttons were not visible anymore if the image field was not in a repeater (white font color on white ground).

The look of the buttons is set in two places:

a) wire/modules/Inputfield/InputfieldImage/InputfieldImage.module:
'buttonClass' => "ui-button ui-corner-all ui-state-default"

b) wire/modules/AdminTheme/AdminThemeUikit/init.php:
'buttonClass' => "uk-button uk-button-small uk-button-text uk-margin-small-right",

I wonder why b) seems not to be obeyed if the image field is not in a repeater?
I vote for using Uikit-Buttons, if Uikit is the default theme.

**Comment by matjazpotocnik** [comment]
> The look of crop & variations buttons is inconsistent, depending on whether the image field is in a repeater or not.

Yep.

> Besides that, I vote for using Uikit buttons, if Uikit is the default theme.

Generally, agree, but then ALL buttons have to follow this rule. Currently, all buttons have "ui-button ui-corner-all ui-state-default" class applied, just those crop/variations buttons are different. I think it would be much better if all admin themes would simply use "ui-button ui-corner-all ui-state-default", so module developer wouldn't have to check what admin theme is used by the user ...

**Comment by processwired** [comment]
Yes, that sounds reasonable. In this case, the entry in wire/modules/AdminTheme/AdminThemeUikit/init.php:
`'buttonClass' => "uk-button uk-button-small uk-button-text uk-margin-small-right"` is not needed anymore and the look of the buttons is a matter of some css rules: the Uikit button styles could be applied to "ui-corner-all ui-state-default".

**Comment by matjazpotocnik** [comment]
@ryancramerdesign ping

**Comment by matjazpotocnik** [comment]
Fixed. Now links look the same inside and outside of the repeater. Markup is still different in AdminThemUikit then in other two themes, but I can adapt to this.
