### ISSUE TITLE
Missing translation in headlines/page titles

### ISSUE THREAD

**Issue by processwired** [ryancramerdesign/AdminThemeUikit#47]
(This was also [posted in the forum](https://processwire.com/talk/topic/17392-pw-3078-%E2%80%93-more-admin-theme-updates/?tab=comments#comment-152782) - I'm not too sure if I should crosspost it here, but I think it should not get lost).

I think the new admin theme is a big step ahead! I really like it. I'm now starting to play with it and found a small inconsistency in regard to translations:

<img width="290" alt="59d8a0c3a408d_bildschirmfoto2017-10-07um11_38_59 png d5e4f2f39f3aa6b730cd3ab0e8446d67" src="https://user-images.githubusercontent.com/8448399/31564493-4c37e7d8-b063-11e7-93e0-3bbe6f2147f2.png">

In the upper nav bar, "Seiten" (does mean "Pages" in English) is translated by german language pack. "Pages" below this, however, is the page title of the "Pages" page (Page ID 3) inside of "Admin" (Page ID 2). I figured out that "Pages" can be translated as well by editing the "Pages" title, but this page has to be unlocked first in order to edit the title. I'm not sure if everyone who uses this theme knows how to follow these steps to get a fully translated theme. I think this should be handled somewhat more consistent - either the Page title or the translation file  should be used in both cases. To be honest, I wonder if it has any unforeseen side impacts if the titles of "Pages", "Setup", "Modules" and "Access" pages inside of "Admin" are changed?

**Comment by ryancramerdesign** [comment]
Thanks, this was a core issue in AdminThemeFramework class. I've pushed a fix to the core dev branch.
