### ISSUE TITLE
Inputfield Checkbox side by side doesn't span full width

### ISSUE THREAD

**Issue by gmclelland** [ryancramerdesign/AdminThemeUikit#49]
I have two Checkbox fields that are set to 50% width.  They sit side by side, but do not take up the full width.

They're visibility settings are set to "Open when populated + Closed when blank + Load only when opened (AJAX) †"

Here is what they look like on page load:
![edit page scout programs pwoliver test 2017-10-24 09-56-32](https://user-images.githubusercontent.com/40570/31950695-c1f1a7ca-b8a1-11e7-9884-96d32260fa9e.jpg)

Here is what they look like expanded when clicked:
![expanded](https://user-images.githubusercontent.com/40570/31950301-e9db3a2c-b8a0-11e7-99cd-a4c9e3e561ee.jpg)

Here it is correctly displayed when the checkbox field's input setting is "Open"
![correct](https://user-images.githubusercontent.com/40570/31950423-304f7428-b8a1-11e7-96f3-60bb1868fa52.jpg)

Here it is correctly displayed when the checkbox field's input setting is "Closed"
![closed](https://user-images.githubusercontent.com/40570/31950551-786c7a12-b8a1-11e7-9cad-2a4ad4156dc8.jpg)

**Comment by gmclelland** [comment]
Looks like it is missing the .uk-width-1-2@m class on both.

**Comment by gmclelland** [comment]
If I add the .uk-width-1-2@m class to this element, everything seems align and display correctly.

Here is the markup I'm referring to:
![addclass](https://user-images.githubusercontent.com/40570/31952223-bd6dea5c-b8a5-11e7-86cf-d443cb1cc7e7.jpg)

I'm not sure where that class is generated from?

**Comment by gmclelland** [comment]
Not sure if it is needed, but I also noticed the second checkbox(Hide from Menus) doesn't have the class .InputfieldRowLast
![missingclass](https://user-images.githubusercontent.com/40570/31954171-78c2c878-b8aa-11e7-8785-0071c2b13254.jpg)

I also noticed a lot of activity(html changes) when I first click on the checkbox field to expand it.  Here is a recording.  Notice all the purple changes?

![Screencast](https://monosnap.com/file/KTFWalKgVTxrNnvRsz5fA8q5VTkE3b.png)

**Comment by ryancramerdesign** [comment]
Does the issue appear to be that they are ajax loaded? It looks like they work as expected if the ajax loading isn't involved? There actually isn't any reason to make a checkbox field ajax loaded. That option is there for heavy-duty Inputfields or Fieldsets, where ajax load might help the editor to load quicker. But with checkboxes, they are about the lowest overhead Inputfield there is, so it's going to actually increase the overhead to make it ajax loaded. If the problem is isolated to ajax-loaded checkboxes, I don't think it's worth the effort to pursue. But if the problem is for all ajax loaded Inputfields, then we should get a closer look. So far I'm not observing any issues on my ajax loaded fields (images and repeaters), but that's probably not a broad enough test.

**Comment by gmclelland** [comment]
> Does the issue appear to be that they are ajax loaded? It looks like they work as expected if the ajax loading isn't involved?

Yes, this issue only seems to happen when the checkboxes are ajax loaded.  I haven't tested other ajax loaded fields.

> That option is there for heavy-duty Inputfields or Fieldsets, where ajax load might help the editor to load quicker. But with checkboxes, they are about the lowest overhead Inputfield there is, so it's going to actually increase the overhead to make it ajax loaded.

I did not know that.  I'll make sure I don't use ajax for checkboxes.

> If the problem is isolated to ajax-loaded checkboxes, I don't think it's worth the effort to pursue.

No problem.  Just thought I should document the issue just in case someone else runs into it.  I originally noticed the problem when I was trying to help fix the AdminOnSteriods module to be compatible with AdminThemeUikit.  https://github.com/rolandtoth/AdminOnSteroids/issues/59
In that issue regular checkboxes and ajax loaded checkboxes weren't displaying correctly, but we got the issue fixed with AOS and regular checkboxes.

Do you want me to leave this issue open or close it?

**Comment by gmclelland** [comment]
Closing.  The latest commits fix this issue.
