### ISSUE TITLE
Page select button disappears in certain page tree

### ISSUE THREAD

**Issue by franctic-aerobic** [ryancramerdesign/AdminThemeUikit#50]
When editing a page, and under Settings. I try to change the parent page. But the page select button for pages in that page tree shows only for a quarter of second, then disappears.

(The same with another Page List Select type button of the page reference field I have in a template).

**Comment by BitPoet** [comment]
This might be a generic PW issue and not limited to AdminThemeUikit. There's an issue with vanishing page select buttons at processwire/processwire-issues#411 and a [discussion in the forums](https://processwire.com/talk/topic/17547-weird-bug-with-page-ref-fields/).

**Comment by franctic-aerobic** [comment]
I'm closing this issues, due to it being mentioned here: processwire/processwire-issues#411
