### ISSUE TITLE
Feature request: make renderBreadcrumb hookable

### ISSUE THREAD

**Issue by BitPoet** [ryancramerdesign/AdminThemeUikit#51]
It seems a lot of people would like to add features (links, dropouts etc.) to the admin breadcrumb (see e.g. [this forum discussion](https://processwire.com/talk/topic/17452-admin-breadcrumb-dropdown-idea/)), so I feel it would be nice if AdminThemeUikit::renderBreadcrumb was hookable. The computing cost for that should IMHO be negligible, and I'm not aware of another convenient entry point to hook into for customizing the breadcrumb.

**Comment by ryancramerdesign** [comment]
Makes sense to me, thanks. I will include it in today's version update.
