### ISSUE TITLE
InputfieldMarkup missing width class

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/AdminThemeUikit#52]
When creating InputfieldMarkup and set the width, uk-width class is missing:

```
$field = $this->wire('modules')->get('InputfieldMarkup');
$field->columnWidth = 50; //does not work
```

I have to add class manually:

`$field->class       = "uk-width-1-2@m"; `

**Comment by matjazpotocnik** [comment]
It looks like that InputfieldFieldset is also missing the uk-width* classes.

**Comment by ryancramerdesign** [comment]
Thanks, today's version update (coming later) should correct this, but please let me know if you continue to observe the issue.

**Comment by gmclelland** [comment]
Hmm.. I wonder if this is related https://github.com/ryancramerdesign/AdminThemeUikit/issues/49 since the ajax loaded checkboxes are missing the uk-width classes?

**Comment by matjazpotocnik** [comment]
Widths on InputfieldFieldset and InputfieldMarkup are fixed, but I'll leave this open in case it's related.
