### ISSUE TITLE
<code> styling

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/AdminThemeUikit#53]
I think that `:not(pre)>code, :not(pre)>kbd, :not(pre)>samp` is missing

```
overflow: auto;
display: block;
```

![screenshot 2017-11-01 04 51 34_cr](https://user-images.githubusercontent.com/7663992/32259400-9818dbba-bec0-11e7-943b-d3e2558b2fec.jpg)

**Comment by ryancramerdesign** [comment]
Thanks, I have added this and it'll be in today's version.
