### ISSUE TITLE
Pixel rounding

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/AdminThemeUikit#56]
This is Uikit and not specific to PW or ATU, just to mention here. In some situations, especially at uk-width-1-3, there is 1px misalignment at right border (at least in Chrome) due to rounding. It also depends on browser width. 

![screenshot 2017-11-04 07 34 27_cr](https://user-images.githubusercontent.com/7663992/32403126-ecbe2110-c132-11e7-8566-949c92877752.jpg)
 
![screenshot 2017-11-04 07 34 27_cr1](https://user-images.githubusercontent.com/7663992/32403140-30a00e84-c133-11e7-9fb8-d813e1ac0a80.jpg)

I "fixed" that by setting .uk-width-1-3\@m  to `width: calc(100% * 1 / 3.0001);` instead of width: `calc(100% * 1 / 3.001);`

**Comment by ryancramerdesign** [comment]
Nice find! I wonder if you should submit this to the Uikit 3 repo issue reports too? It seems like this will turn up in other places that your fix will be useful for.

**Comment by matjazpotocnik** [comment]
I guess the guys at Uikit have a reason why they have it at 3.001 so I'm not sure if this would help. Nevertheless I submitted an issue there.
