### ISSUE TITLE
Unwanted underline on button

### ISSUE THREAD

**Issue by gmclelland** [ryancramerdesign/AdminThemeUikit#57]
When I click the "Insert Image" button on CKeditor it opens a modal that contains a button "Upload Image."  This button is receiving an underline when hovered.

![edit page about us pwoliver test 2017-11-06 12-01-22](https://user-images.githubusercontent.com/40570/32456287-af9af204-c2ea-11e7-9c45-7847bd4d770c.jpg)

**Comment by matjazpotocnik** [comment]
@gmclelland I think this is fixed in 3.0.84

**Comment by gmclelland** [comment]
Yes, it looks it fixed now.  Thanks
