### ISSUE TITLE
Markdown code displaying block rather than inline

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/AdminThemeUikit#62]
I have this in Tracy's config settings. Note the markdown backtick ` for defining inline code. 
```
$f->notes = __('Initially configured for SublimeText (`subl://open/?url=file://%file&line=%line`). Change to work with your favorite editor.', __FILE__);
```
In the default theme this results in this which is ok, even though the code font is larger than the rest (which could be improved).

![screen shot 2017-11-14 at 3 56 36 pm](https://user-images.githubusercontent.com/871211/32811428-743748fa-c954-11e7-8a88-352869b11e19.png)

But in the UiKit theme it looks like this which really breaks the flow of the note.

![screen shot 2017-11-14 at 3 48 42 pm](https://user-images.githubusercontent.com/871211/32811266-9dd11a34-c953-11e7-905a-cb800db620c9.png)

It should really look like this:

![screen shot 2017-11-14 at 3 51 26 pm](https://user-images.githubusercontent.com/871211/32811292-bbd80c68-c953-11e7-90d3-5004e170ed3e.png)

This is due to the `display:block` here:
https://github.com/ryancramerdesign/AdminThemeUikit/blob/4ed79c93fc2319a8a8e1f4ad701d0455d9ca638d/uikit/dist/css/uikit.pw.css#L108

**Comment by matjazpotocnik** [comment]
It's because of this: https://github.com/ryancramerdesign/AdminThemeUikit/issues/53

**Comment by matjazpotocnik** [comment]
@adrianbj, Ryan removed `display: block` but that unfortunately breaks the layout in "my" case, see the picture in #53

**Comment by adrianbj** [comment]
@matjazpotocnik - thanks for pointing out the change - I hadn't noticed yet, but it does fix my issue. Is the problem in the screenshot in #53 the overflow in the second code block? If so, couldn't that be handled with word-wrap etc?

**Comment by matjazpotocnik** [comment]
Yes, the overflow. word-wrap doesn't help, removing `white-space: no-wrap` helps a bit, but it's not really what is intended. I added `style="display: block"` to the `<code>` and it looks ok. So you may close this issue as far as I'm concerned. Sorry for troubles I made.

**Comment by adrianbj** [comment]
No problem - I always find that wrap stuff a little trial and error, but I use this successfully for some things. Not sure if it will suit your needs or though.

```
    white-space: pre;           /* CSS 2.0 */
    white-space: pre-wrap;      /* CSS 2.1 */
    white-space: pre-line;      /* CSS 3.0 */
    white-space: -pre-wrap;     /* Opera 4-6 */
    white-space: -o-pre-wrap;   /* Opera 7 */
    white-space: -moz-pre-wrap; /* Mozilla */
    white-space: -hp-pre-wrap;  /* HP Printers */
    word-wrap: break-word;      /* IE 5+ */
```

I will close this issue, but the reported problem is now fixed.
