### ISSUE TITLE
z-index of masthead navigation bar is higher than modal window z-index

### ISSUE THREAD

**Issue by incognitoms** [ryancramerdesign/AdminThemeUikit#68]
The small white triangle is displayed above the modal's head, see attached gif animation:
![pw](https://user-images.githubusercontent.com/7930439/34001377-1b56a1b4-e0f0-11e7-85d6-e457c655953e.gif)

**Comment by matjazpotocnik** [comment]
I'm not seeing this here...

**Comment by processwired** [comment]
This has been fixed in one of the last commits, thanks. Closed.

**Comment by incognitoms** [comment]
This has been fixed in one of the last commits, thanks.
