### ISSUE TITLE
Css issues?

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/AdminThemeUikit#7]
![screenshot 2017-03-08 20 05 10_cr](https://cloud.githubusercontent.com/assets/7663992/23719227/cdd9ea3c-043a-11e7-8f99-89125a353f66.png)

Is it intended that Cancel button is at the "next line"?

**Comment by ryancramerdesign** [comment]
I think I resolved all these button issues (which were appearing in multiple spots) last week, but please let me know if you see more anywhere else. Thanks.
