### ISSUE TITLE
Column width (again)

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/AdminThemeUikit#73]
The latest commit https://github.com/processwire/processwire/commit/461152a8cdb8650ab923f4c061482d091f532414#diff-694d66db0292167fe3e3397027f4737bR24 breaks 25% / 75% layout. Before that commit, the widths were calculated as 1/4 and 3/4, now it is 1/4 and 2/3. Related to https://github.com/processwire/processwire-issues/issues/480? My limited testing shows that adding `'75%' => '3-4',` to the $ukGridWidths array fix the issue.

Please reconsider setting the column widths via JS to the widths specified in the field settings.

**Comment by ryancramerdesign** [comment]
Thanks, I have corrected this and it will be in this weeks updates.

**Comment by matjazpotocnik** [comment]
Thank you.
