### ISSUE TITLE
Unaligned ui-icon-extlink in template edit

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/AdminThemeUikit#74]
Chrome:
![screenshot 2018-02-03 09 27 56_cr_chrome](https://user-images.githubusercontent.com/7663992/35765602-b5b2b1cc-08c7-11e8-9415-a4d62897c43c.jpg)

Firefox:
![screenshot 2018-02-03 09 20 17_cr_ff](https://user-images.githubusercontent.com/7663992/35765603-b5cc4ed4-08c7-11e8-843a-47aa3df345ca.jpg)

I fixed this by modifying background-position on .ui-icon-extlink from `-32px -80px` to `-32px -76px`

**Comment by gmclelland** [comment]
Just tested.  This is still an issue in 3.0.94.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign ping

**Comment by ryancramerdesign** [comment]
Thanks, I have fixed this issue (switching to an fa-edit icon and inline-block) and it will appear in the next update.

**Comment by matjazpotocnik** [comment]
Thank you.
