### ISSUE TITLE
Column width

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/AdminThemeUikit#8]
As seen on the screenshots, columns are not "evenly" distributed. All six columns (from Wire to Files) are 16% wide. In the Default admin theme the last column is 20%, so that 5*16+20 sums nicely at 100%.

![screenshot 2017-03-08 07 13 35_cr](https://cloud.githubusercontent.com/assets/7663992/23767346/8c99f82c-0508-11e7-96d1-46172e8c424d.png)
![screenshot 2017-03-08 07 11 24_cr_cr](https://cloud.githubusercontent.com/assets/7663992/23767347/8cb1e630-0508-11e7-977f-1ed0f27846a4.png)

**Comment by ryancramerdesign** [comment]
The AdminThemeUikit uses the Uikit grid rather than PW's width percentages. For most cases the result ends up the same, but there are going to be a few edge cases where it doesn't, and this is one of them. I think that your last column would also have to be 16% (rather than 20%) in order to get the same result as in AdminThemeDefault. That's because 16% translates to class `uk-width-1-6`, which is 16.66%, and uk-width-1-6 is the smallest width grid unit Uikit provides.

**Comment by matjazpotocnik** [comment]
The last column actually is 16% wide, but AdminThemeDefault fix that and make the last column 20% wide that sums to 100% and columns are aligned neatly. AdminThemeUikit does not do that. Another example: three colums, first 38%, second 38%, third 24%, that sums 100%. In AdminThemeUikit this is "translated" to `uk-width-1-3@m` (33%) for the first and second column and to `uk-width-1-5@m` (20%) for the third column, that sums to 86%. That is "wrong" too. If we stick with that behaviour, a lot of modules will look very strange...

**Comment by noonesboy** [comment]
I'm having a similar issue but it is much more straightforward. The 'Title' field is 35% wide, the 'Page Headline' is 65% wide for a perfect 100%. However this still breaks the line. If I put them both at much smaller sizes they both fit but there is a large gap at the end.

<img width="1376" alt="screen shot 2017-10-02 at 1 09 23 pm" src="https://user-images.githubusercontent.com/1612665/31097180-48b36356-a773-11e7-84d1-fcf78a227b73.png">

**Comment by matjazpotocnik** [comment]
@skylundy 35% / 65% should work. Here is the table of percentage widths so that columns are correctly distributed in AdminThemeUikit.

```
 80 % | 20 %
 4/5  | 1/5
------+------
 75 % | 25 %
 3/4  | 1/4
------+------
 70 % | 30 %
 3/4  | 1/4
------+------
 67 % | 33 %
 2/3  | 1/3
------+------
 66 % | 34 %
 2/3  | 1/3
------+------
 65 % | 35 %
 2/3  | 1/3
------+------
 60 % | 40 %
 3/5  | 2/5
------+------
 50 % | 50 %
 1/2  | 1/2


 20 % | 20 % | 60 %
 1/5  | 1/5  | 3/5
------+------+------
 20 % | 40 % | 40 %
 1/5  | 2/5  | 2/5
------+------+------
 25 % | 25 % | 50 %
 1/4  | 1/4  | 1/2
------+------+------
 33 % | 33 % | 34 %
 1/3  | 1/3  | 1/3


 25 % | 25 % | 25 % | 25 %
 1/4  | 1/4  | 1/4  | 1/4
------+------+------+------
 20 % | 20 % | 20 % | 40 %
 1/5  | 1/5  | 1/5  | 1/5
------+------+------+------
 16 % | 16 % | 16 % | 52 %
 1/6  | 1/6  | 1/6  | 1/2
------+------+------+------
 17 % | 17 % | 33 % | 33 %
 1/6  | 1/6  | 1/3  | 1/3


 20 % | 20 % | 20 % | 20 % | 20 %
 1/5  | 1/5  | 1/5  | 1/5  | 1/5
------+------+------+------+------
 16 % | 16 % | 16 % | 16 % | 36 %
 1/6  | 1/6  | 1/6  | 1/6  | 1/3


 17 % | 17 % | 17 % | 17 % | 17 % | 15 %
 1/6  | 1/6  | 1/6  | 1/6  | 1/6  | 1/6
------+------+------+------+------+------
 16 % | 17 % | 17 % | 17 % | 17 % | 16 %
 1/6  | 1/6  | 1/6  | 1/6  | 1/6  | 1/6

```
