### ISSUE TITLE
Page tree sidebar status not remembered after page reload

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/AdminThemeUikit#9]
If you have the page tree sidebar open, and the nav sidebar closed and reload the page, it reverts to nav sidebar open and page tree sidebar closed.

**Comment by ryancramerdesign** [comment]
This is expected, I'm not sure there's anything we can do about that. Though I'll see if the layout plugin supports remembering this stuff with a cookie or something. But manually reload/refreshing URLs in the admin is usually something to be avoided for most users, though I know those of us developing stuff for/in the admin, we have to do it a lot.

**Comment by adrianbj** [comment]
Another related thing I am seeing right now is that if I am editing a page (with tree sidebar open) and I reload, I don't go back to editing that page. I think this would be dealt with if you adopt the pushstate stuff so that the address bar actually contains the edit link.

If I enter http://pwtest.dev/admin/page/edit/?id=1019 in the browser directly, it loads the page as it should be, with the sidebar open and the page ready for edit, so if pushstate took care of updating the address bar, I think it would really help here.

It would also be nice to store the width of the sidebar in LocalStorage (or perhaps a cookie).

**Comment by adrianbj** [comment]
As I use this more and more, I definitely think the sidebar width needs to either be configurable, or needs to be stored in cookies/local storage. I find it way too wide and having to adjust each time I come back to the admin is a pain :)

**Comment by ryancramerdesign** [comment]
The width and collapsed/open state should be remembered with a cookie now, but unfortunately it doesn't seem to work most of the time. This is one I put in last week. It's using the jquery.layout.state.js plugin which is a plugin designed to make the Layout library remember these things. As far as I can tell, it's just not working how it should though. When I'm lucky, it works half the time. I guess this will be one of those things we'll have it get in there and debug why the plugin isn't working, or just write our own... leaning towards writing our own.

**Comment by adrianbj** [comment]
Actually it seems to be working pretty well here at the moment. I am not sure what changed from a couple of days ago. I'll keep an eye on things and let you know.
